### ISSUE TITLE
Does not work with forks, does it?

### ISSUE THREAD

**Issue by LorenzoBettini** [turing85/publish-report#80]
I seem to understand that, due to required permissions, this does not work with PRs from private forks.

An example of failure here: https://github.com/LorenzoBettini/github-actions-publish-test-results-example/pull/1

**Comment by turing85** [comment]
Nope. The problem is the rights management within github. We cannot run code from forks in the context of the repository. There is a way to make it work, but this requires workflow calls.

**Comment by LorenzoBettini** [comment]
The action you use under the hood seems to support that, doesn't it?

**Comment by turing85** [comment]
As I said: you'd need another workflow, as shown in the [`test-reporting` action](https://github.com/phoenix-actions/test-reporting?tab=readme-ov-file#recommended-setup-for-public-repositories). It seems possible, but I haven't fully thought it through. I am not sure that this is something that should or could be done in an action since a 2nd workflow is needed.

**Comment by LorenzoBettini** [comment]
But then, how to refer to the right artifact to download?

**Comment by turing85** [comment]
The [`actions/download-artifact` action (`github.com`)](https://github.com/actions/download-artifact) has a `run-id` parameter. The [`workflow_run` payload (`docs.github.com`)](https://docs.github.com/en/webhooks/webhook-events-and-payloads#workflow_run) that is received by a workflow that runs on 
```yaml
workflow_run:
  ...
  types:
    - completed
```

also has an `id` field. So with this information, it should be possible to download the artifact in question. [This `stackoverflow.com` answer](https://stackoverflow.com/a/77984007/4216641) has a minimal example of a correspoding call to `actions/download-artifact`.

Hope this helps.

**Comment by LorenzoBettini** [comment]
But does your action honor run-id, if specified, when downloading the artifact? I mean I seem to understand that your action is a composite one and uses download-artifact. Or are you suggesting to use the commit sha in the artifact name when uploading and then downloading?

**Comment by turing85** [comment]
Right now, it does not. If one wants to add the capability to this action, one would have to add a corresponding `run-id` parameter to download the artifact and most probably a `pr-number` parameter to pass along to [`marocchino/sticky-pull-request-comment`](https://github.com/marocchino/sticky-pull-request-comment). We get the `run-id` of the caller for free. Everything else (including the pr-number) we'd have to transfer via an artifact.

**Comment by LorenzoBettini** [comment]
Mh.. so there's basically no way to achieve that with another workflow (the only way to make it work with forks).

**Comment by turing85** [comment]
The only way to achieve this IS another workflow. But a single action exection cannot "span" multiple workflows. The workflows have to communicate. And this communication happends through a trigger event and artifacts (that are downloaded with the information given in the trigger event).

**Comment by LorenzoBettini** [comment]
I understand that. But from what you said I also seem to understand that I cannot achieve the desired result by using this action in another workflow in the current state.

**Comment by turing85** [comment]
Correct. As I said: we would need at least two more parameter. One for the `run-id`, one for the `pr-number`.

**Comment by LorenzoBettini** [comment]
Ok, thanks for the confirmation. In case you work on that, I'll be glad to test it.

**Comment by turing85** [comment]
@all-contributors please add @LorenzoBettini for question and idea

**Comment by turing85** [comment]
@LorenzoBettini I implemented the parameters on branch [`feature/run-id-and-pr-number`](https://github.com/turing85/publish-report/tree/feature/run-id-and-pr-number). Can you test it and see whether this is what you need?

**Comment by turing85** [comment]
There will be a downside as far as I can see. [`phoenix-actions/test-reporting`](https://github.com/phoenix-actions/test-reporting) does not support a run-id, run-number or similar. So the check will not be "attached" to the PR. This is not really a limitation of the `test-reporting` action, but a limitation of GitHub's rest api. The [corresponding endpoint](https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#create-a-check-run--parameters) does not allow to set the `run_id` (or similar).

**Comment by LorenzoBettini** [comment]
I'll probably test it next week, thanks!

I saw other similar actions attach the output to the PR. Or do you mean something else?

**Comment by turing85** [comment]
I mean the check "artifact". This is bound to the run-id that creates the check. Since we need a separate workflow to upload the check (i.e. the report, not the artifact, but the actual report; e.g. [this](https://github.com/turing85/publish-report/actions/runs/9472179216/job/26097250382)), it will not be bound to the pr run, but to the "downstream" workflow. This, in return, means that we cannot set a required check in the pipeline rules to said artifact.

**Comment by turing85** [comment]
@LorenzoBettini were you able to test the feature?

**Comment by LorenzoBettini** [comment]
> @LorenzoBettini were you able to test the feature?

Sorry, not yet. I'll try in the next few days.

**Comment by turing85** [comment]
> > @LorenzoBettini were you able to test the feature?
> 
> Sorry, not yet. I'll try in the next few days.

Just let me know when you've tested it and if there are any issues. If everything is fine, I'll prepare a new release.

**Comment by turing85** [comment]
I was able to test the fix. The setup is non-trivial, but it works. The [`README.md` has a howto-section](https://github.com/turing85/publish-report?tab=readme-ov-file#support-for-fork-prs). I am in the process of building release `2.1.0`.

**Comment by turing85** [comment]
[`v.2.1.0` (`github.com`)](https://github.com/marketplace/actions/publish-test-report) has been released.

**Comment by turing85** [comment]
@LorenzoBettini [Here (`github.com`)](https://github.com/citrusframework/citrus-remote/tree/main/.github/workflows) are three sample workflows that show a working setup.

**Comment by LorenzoBettini** [comment]
@turing85 thanks for the updates. I'll have a look at the readme file. The examples you link look a bit involved. Or are the examples minimal?

**Comment by turing85** [comment]
@LorenzoBettini As I have already said: we need separate workflows, and we need to transport information from one workflow to another (from the actual `build`  to the workflow that does the test upload and the comment-update). I am not sure how the action reacts if no comment is present. You can try it out and see what happens if you only use two workflows (one for the build, one for the comment afterwards). But this is the bare minimum. The recommended minimum (with three workflows) is in the readme.
